import AppProviders from "@/providers/AppProviders";
import type { Metadata } from "next";
import { Cinzel_Decorative, Manrope } from "next/font/google";

import { cn } from "@/lib/utils";
import { ReactNode } from "react";
import { Toaster } from "sonner";
import "./globals.css";

const cinzel = Cinzel_Decorative({
  subsets: ["latin"],
  variable: "--font-cinzel",
  weight: ["400", "700", "900"],
  display: "swap",
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          cinzel.variable,
          manrope.className,
          "antialiased bg-[#F0F8FF]"
        )}
      >
        <AppProviders>{children}</AppProviders>
        <Toaster position="bottom-right" richColors />
      </body>
    </html>
  );
}
